#!/usr/bin/env bash
# to 
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
ip=$2
username=$3
ssh_key_path=$4


export SCP_OPTIONS="-o StrictHostKeyChecking=no"


scp -i "$ssh_key_path" "$file_path" "$username@$ip:~/"

if [ $? -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "File transfer failed!"
fi

